PATCH http://localhost:3000/tasks/6/status
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "status": "IN_PROGRESS"
}

### Delete a task
DELETE http://localhost:3000/tasks/13
Accept: application/json
Authorization: Bearer {{user1_token}}

### Get task by id
GET http://localhost:3000/tasks/2
Accept: application/json
Authorization: Bearer {{user1_token}}

### Create task
POST http://localhost:3000/tasks
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{user1_token}}

title=Title&description=orm task description

### Get all tasks
GET http://localhost:3000/tasks
Accept: application/json
Authorization: Bearer {{user1_token}}

### Get filtered tasks
GET http://localhost:3000/tasks?search=Title
Accept: application/json
Authorization: Bearer {{user1_token}}

###