POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "user2",
  "password": "!123Abcdef"
}

###
POST http://localhost:3000/auth/signup
Content-Type: application/json
{
  "username": "user1",
  "password": "!123Abcdef"
}

###
